# Generated by Django 5.1.6 on 2025-08-03 05:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_remove_order_products_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top_of_category',
            field=models.BooleanField(default=False, verbose_name='Top of his category'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trend',
            field=models.BooleanField(default=False, verbose_name='Trend'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image 1'),
        ),
    ]
