# Generated by Django 5.1.6 on 2025-02-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_order_shipping_user_review_payment_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='ecommerce_app.product'),
        ),
    ]
