# Generated by Django 5.1.6 on 2025-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_remove_payment_payment_method_payment_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='detail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
