# Generated by Django 5.1.6 on 2025-02-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_payment_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Other', 'Other')], default='Credit Card', max_length=20),
        ),
    ]
